# -*- coding: utf-8 -*-
"""Calc

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rrcBg_p17cZ4B-2o9hTL9NCTS_GKDYCa
"""

import numpy as np
a=int(input("Enter a number"))
b=int(input("Enter another number"))
print("1 for addition")
print("2 for subtraction")
print("3 for multiplication")
print("4 for division")
choice=int(input("Choose one out of 4 operations"))
if choice==1:
    print(a+b)
elif choice==2:
    print(a-b)
elif choice==3:
    print(a*b)
elif choice==4:
    print(a/b)
else :
  print("Invalid choice")