# -*- coding: utf-8 -*-
"""EDA

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lNa6xJ_SRk0NetESekuA2XmvfEoTcPKm
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/train.csv")

df.head(2)

df.describe()

df['Age'].describe()

df.drop_duplicates()

df['Age'].plot(kind='hist',bins=20)

df['Age'].plot(kind='kde')

df['Age'].isnull().sum()/len(df['Age'])

df['Fare'].describe()

a=df['Age'].isnull().sum()

df.drop(a)

df['Embarked'].value_counts().plot(kind='bar')

df

sns.heatmap(pd.crosstab(df['Survived'],df['Pclass'],normalize='columns')*100)

pd.crosstab(df['Survived'],df['Embarked'],normalize='columns')*100

# survived and age
df[df['Survived'] == 1]['Age'].plot(kind='kde',label='Survived')
df[df['Survived'] == 0]['Age'].plot(kind='kde',label='Not Survived')
plt.legend()
plt.show()

df[df['Name'].str.contains('Sage')]

"""

**Some operations **
"""

df.head()

df.tail()

df.sample(2)

df.shape

df.size

df.columns

df.index

df['Fare'].dtype
df.dtypes

df.info()

df.isnull()

df[['Age', 'Cabin']].isnull()

df[['Age']].notnull()

df[['Age']].sum()

df_dropped = df.dropna()
display(df_dropped.head())

display(df.duplicated().head())

# nunique(): Returns the number of unique values for each column (or for a Series).
print("Number of unique values per column:")
display(df.nunique())

df['Embarked'].unique()

df['Embarked'].value_counts()

df.sort_values(by='Age').head()

df['Age'].min()

df['Age'].max()

df['Age'].mean()

df['Age'].median()

df['Embarked'].mode()

df['Age'].std()

df['Age'].var()

df.corr(numeric_only=True)

df.cov(numeric_only=True)

df.groupby('Pclass')['Age'].mean()

df.count()

#Access a group of rows and columns by label(s).
df.loc[0:2, ['Name', 'Age']]

#Access a group of rows and columns by integer position(s).
df.iloc[0:3, [3, 5]]

df.query('Age > 30').head()

df_renamed = df.rename(columns={'PassengerId': 'ID'})
print("DataFrame with 'PassengerId' renamed to 'ID' (first 2 columns):")
display(df_renamed.head()[['ID', 'Survived']])

df_no_cabin = df.drop(columns=['Cabin'])
display(df_no_cabin.head())

import matplotlib.pyplot as plt
import seaborn as sns
df['Age'].hist(bins=20)
plt.title('Histogram of Age')
plt.xlabel('Age')
plt.ylabel('Frequency')
plt.show()

df.boxplot(column='Age', by='Pclass')
plt.title('Box Plot of Age by Pclass')
plt.xlabel('Passenger Class')
plt.ylabel('Age')
plt.show()

sns.histplot(df['Age'].dropna(), bins=20)
plt.title('Seaborn Histogram of Age')
plt.xlabel('Age')
plt.ylabel('Density / Count')
plt.show()

sns.scatterplot(x='Age', y='Fare', data=df, hue='Survived')
plt.title('Scatter Plot of Age vs Fare by Survival')
plt.xlabel('Age')
plt.ylabel('Fare')
plt.show()

sns.countplot(x='Pclass',data=df)
plt.title('Count of Passengers by Pclass')
plt.xlabel('Passenger Class')
plt.ylabel('Count')
plt.show()

#make pairwise relationships in a dataset.
sns.pairplot(df[['Age', 'Fare', 'Survived']].dropna(), hue='Survived',kind='kde')

sns.heatmap(df.corr(numeric_only=True), annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap')
plt.show()

"""⚓

***LOAN APPROVAL ANALYSIS***
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/loan_sanction_train.csv")
df

df.head(2)

sns.countplot(x='Loan_Status',data=df)
plt.title('Distribution of Loan Status')
plt.xlabel('Loan Status')
plt.ylabel('Count')
plt.show()

df.drop_duplicates(inplace=True)
df

numerical_cols = ['ApplicantIncome', 'CoapplicantIncome', 'LoanAmount', 'Loan_Amount_Term']
sns.histplot(data=df, x=col, hue='Loan_Status', kde=True)
plt.title(f'Distribution of {col} by Loan Status')
plt.xlabel(col)
plt.ylabel('Count')
plt.show()
sns.countplot(data=df, x='Credit_History', hue='Loan_Status')
plt.title('Loan Status Distribution by Credit History')
plt.xlabel('Credit History (1: Good, 0: Bad)')
plt.ylabel('Count')
plt.show()

df.groupby('Loan_Status')[numerical_cols+['Credit_History']].describe()

cross_tab_gender = pd.crosstab(df['Gender'], df['Loan_Status'], normalize='columns') * 100
cross_tab_gender.plot(kind='bar')
plt.title('Loan Status Distribution by Gender')
plt.xlabel('Gender')
plt.ylabel('Percentage')
plt.legend(title='Loan Status')
plt.show()

a=pd.read_excel("/content/file.xlsx")
a

a.describe()

a.info()

