# -*- coding: utf-8 -*-
"""matplot and seaborn

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1w7KM4S1acNBWxgJ6Z6n07vnLGR_vh7rJ

🔥

***Matplot***
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

price=[48000,54000,57000,40000,47000,49000]
year=[2015,2016,2017,2018,2019,2020]
plt.plot(year,price)

a=pd.read_csv("/content/sharma-kohli.csv")
a
plt.plot(a["index"],a["V Kohli"])

plt.plot(a["index"],a["V Kohli"])
plt.plot(a["index"],a["RG Sharma"])

#labeling x&y axis
plt.plot(a["index"],a["V Kohli"])
plt.plot(a["index"],a["RG Sharma"])
plt.title("Rohit Sharma vs Virat Kohli")
plt.xlabel("Season")
plt.ylabel("Runs")

#for color purpose
plt.plot(a["index"],a["V Kohli"],color='blue')
plt.plot(a["index"],a["RG Sharma"],color="magenta")
plt.title("Rohit Sharma vs Virat Kohli")
plt.xlabel("Season")
plt.ylabel("Runs")

#for dotted and solid lines
plt.plot(a["index"],a["V Kohli"],color='blue',linestyle='solid',linewidth=3)
plt.plot(a["index"],a["RG Sharma"],color="magenta",linestyle='dashdot',linewidth=2)
plt.title("Rohit Sharma vs Virat Kohli")
plt.xlabel("Season")
plt.ylabel("Runs")

#for dotted and solid lines with marker in lines
plt.plot(a["index"],a["V Kohli"],color='blue',linestyle='solid',linewidth=3,marker='D',markersize=11)
plt.plot(a["index"],a["RG Sharma"],color="magenta",linestyle='dashdot',linewidth=2,marker='o')
plt.title("Rohit Sharma vs Virat Kohli")
plt.xlabel("Season")
plt.ylabel("Runs")
plt.legend(["Virat Kohli","Rohit Sharma"])

#add label on any location in graph
plt.plot(a["index"],a["V Kohli"],color='blue',linestyle='solid',linewidth=3,marker='D',markersize=11,label='Virat')
plt.plot(a["index"],a["RG Sharma"],color="magenta",linestyle='dashdot',linewidth=2,marker='o',label='Rohit')
plt.title("Rohit Sharma vs Virat Kohli")
plt.xlabel("Season")
plt.ylabel("Runs")
plt.legend(loc='upper right')

price=[48000,54000,57000,40000,47000,49000]
year=[2015,2016,2017,2018,2019,2020]
plt.plot(year,price)
plt.xlim(2015,2020)
plt.ylim(40000,60000)

# for making grid
plt.plot(a["index"],a["V Kohli"],color='blue',linestyle='solid',linewidth=3,marker='D',markersize=11,label='Virat')
plt.plot(a["index"],a["RG Sharma"],color="magenta",linestyle='dashdot',linewidth=2,marker='o',label='Rohit')
plt.title("Rohit Sharma vs Virat Kohli")
plt.xlabel("Season")
plt.ylabel("Runs")
plt.grid()

"""**binary analysis
numerical vs numerical
use case- finding corelation**
"""

#plt.scatter function
x=np.linspace(-10,10,50)
y=10*x+3+np.random.randint(0,300,50)
y

plt.scatter(x,y)

df=pd.read_csv("/content/batter.csv")
df=df.head(50)
df

plt.scatter(df['avg'],df['strike_rate'],color='red')
plt.title("Avg vs Strike Rate")
plt.xlabel("Avg")
plt.ylabel("Strike Rate")

#size
tips=sns.load_dataset("tips")

#slower
plt.scatter(tips['total_bill'],tips['tip'],s=tips['size']*20)

"""**barchart**"""

#simple bar chart
childern=[10,20,30,40,50]
colors=['red','green','blue','yellow','orange']
plt.bar(colors,childern,color=colors)

df=pd.read_csv("/content/sharma-kohli.csv")
df

"""**IPL Analysis**"""

a=pd.read_csv("/content/ipl.zip")
a

# Calculate total runs scored by each batting team
team_runs = a.groupby('bat_team')['runs'].sum().sort_values(ascending=False)
print("\nTotal runs scored by each team (batting):")
display(team_runs)

# Calculate total runs conceded by each bowling team
team_runs_conceded = a.groupby('bowl_team')['runs'].sum().sort_values(ascending=False)
print("\nTotal runs conceded by each team (bowling):")
display(team_runs_conceded)

# Visualize total runs scored by each team
plt.figure(figsize=(12, 6))
sns.barplot(x=team_runs.index, y=team_runs.values, palette='viridis')
plt.xticks(rotation=90)
plt.title('Total Runs Scored by Each Team')
plt.xlabel('Team')
plt.ylabel('Total Runs')
plt.show()

# Top 10 Run-Scorers
top_run_scorers =a.groupby('batsman')['runs'].sum().sort_values(ascending=False).head(10)
print("\nTop 10 Run Scorers:")
display(top_run_scorers)
# Visualize Top 10 Run-Scorers
plt.title('Top 10 Run Scorers in IPL')
plt.xlabel('Player')
plt.ylabel('Total Runs')

# Top 10 Wicket-Takers
# Count wickets only when a wicket event occurred (runs=0, wicket=1) or if it's explicitly a wicket
wickets_df = a[a['wickets'] == 1]
top_wicket_takers = wickets_df.groupby('bowler')['wickets'].count().sort_values(ascending=False).head(10)
print("\nTop 10 Wicket Takers:")
display(top_wicket_takers)
sns.barplot(x=top_wicket_takers.index, y=top_wicket_takers.values, palette='crest')
# Visualize Top 10 Wicket-Takers
plt.title('Top 10 Wicket Takers in IPL')
plt.xlabel('Player')
plt.ylabel('Total Wickets')
9plt.show()

"""

✈

### ***Seaborn***"""

import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

tips=sns.load_dataset('tips')
tips

#scatter plot
sns.scatterplot(data=tips,x='total_bill',y='tip',hue='sex',style='time',size='size')

s=sns.load_dataset('iris')
s

sns.scatterplot(data=s,x='sepal_length',y='sepal_width',hue='species')

sns.scatterplot(data=s,x='petal_length',y='petal_width',hue='species')

#plotly function take dataset from gapminder line graph
gap=px.data.gapminder()
temp_df=gap[gap['country']=='India']
temp_df

#axes fuction
sns.lineplot(data=temp_df,x='year',y='lifeExp')

sns.relplot(data=temp_df,x='year',y='lifeExp',hue='country',style='continent',size='continent',kind='line')

temp_df=gap[gap['country'].isin(['India','Brazil','Germany'])]
temp_df

temp_df=gap[gap['country'].isin(['India','China','Pakistan'])]
temp_df

sns.relplot(data=temp_df,x='year',y='lifeExp',hue='country',kind='line')

#work with replot only
sns.relplot(data=tips,x='total_bill',y='tip',kind='line',col='sex',row='day')

sns.relplot(data=gap,x='lifeExp',y='gdpPercap',kind='scatter',col='year',col_wrap=3)

#plotting histogram
sns.histplot(data=tips,x='total_bill')

sns.displot(data=tips,x='total_bill',kind='kde')

sns.displot(data=tips,x='total_bill',kind='hist',bins=4)

sns.displot(data=tips, x='tip', kind='hist',hue='sex')

sns.displot(data=tips, x='tip', kind='hist',hue='sex',element='step')

"""## Sales Data Analysis Dashboard

"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

a=pd.read_csv('/content/sales_data_sample.csv',encoding='unicode_escape')
a.head(2)

a['ORDERDATE'] = pd.to_datetime(a['ORDERDATE'])
a['ORDER_MONTH'] = a['ORDERDATE'].dt.to_period('M')
monthly_sales = a.groupby('ORDER_MONTH')['SALES'].sum().reset_index()
monthly_sales['ORDER_MONTH'] = monthly_sales['ORDER_MONTH'].dt.to_timestamp()

sns.lineplot(data=monthly_sales, x='ORDER_MONTH', y='SALES')
plt.title('Monthly Sales Trend')
plt.xticks(rotation=90)
plt.show()

regional_sales = df_sales.groupby('Region')['Sales'].sum()

sns.barplot(x=regional_sales.index, y=regional_sales.values)
plt.title('Regional Sales Comparison')
plt.xlabel('Region')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.show()

overall_profit = df_sales['Profit'].sum()
regional_profit = df_sales.groupby('Region')['Profit'].sum()
product_profit = df_sales.groupby('Product')['Profit'].sum()

sns.lineplot(x=monthly_profit.index, y=monthly_profit.values)
plt.title('Monthly Profit Trend')
plt.xlabel('Month')
plt.ylabel('Total Profit')
plt.xticks(rotation=90)
plt.show()

"""**COVID 19**"""

df=pd.read_csv("/content/covid.zip")
df = df[df['country'] != "All"]
df

df.head(2)

country_cases = df.groupby('country')['Cases'].sum()
country_cases.head(10)

sns.barplot(x=country_cases.index[:10], y=country_cases.values[:10])
plt.xlabel('Country')
plt.ylabel('Total Cases')
plt.xticks(rotation=90)
plt.show()

sns.barplot(x=total_recovered_per_country.index[:10], y=total_recovered_per_country.values[:10])
plt.xlabel('Country')
plt.ylabel('Total Recovered Cases')
plt.xticks(rotation=90)
plt.show()

total_recovered_per_country = df.groupby('country')['Recovered'].sum()
total_deaths_per_country = df.groupby('country')['Deaths'].sum()

plt.figure(figsize=(12, 6))
sns.barplot(x=total_deaths_per_country.index[:10], y=total_deaths_per_country.values[:10])
plt.xlabel('Country')
plt.ylabel('Total Deaths')
plt.xticks(rotation=90)
plt.show()

covid_numerical_df = df[['population', 'Cases', 'Recovered', 'Deaths', 'Tests']]
correlation_matrix_covid = covid_numerical_df.corr()
sns.heatmap(correlation_matrix_covid, annot=True, cmap='coolwarm')
plt.title('Correlation Heatmap of COVID-19 Data')
plt.show()

