# -*- coding: utf-8 -*-
"""Pandas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nj9widizYUfjY4a8MmMLsHkomfDeYU41

**STUDENTS**
"""

import pandas as pd

z=pd.read_csv("/content/Student.zip")
z

z ["Average"]=z[["Std_StudyHours", "Std_Marks"]].mean(axis=1)
print(z[["Std_Name","Average"]])

top10=z.nlargest(10,"Std_Marks")
print(top10)

print("Maximum marks for ZOOLOGY:", z[z["Std_Branch"] == "ZOOLOGY"]["Std_Marks"].max())
print("Maximum marks for COMPUTER SCIENCE:", z[z["Std_Branch"] == "COMPUTER SCIENCE"]["Std_Marks"].max())
print("Maximum marks for BIOLOGY:", z[z["Std_Branch"] == "BIOLOGY"]["Std_Marks"].max())

def get_grade(marks):
    if marks >= 90:
      return "A"
    elif marks >= 80:
      return "B"
    elif marks >= 70:
      return "C"
    elif marks >= 60:
      return "D"
    else:
      return "E"
z["Grade"] = z["Std_Marks"].apply(get_grade)
print(z[["Std_Name", "Std_Marks", "Grade"]])

z.describe()

"""**EMPLOYEE**"""

import pandas as pd
a=pd.read_csv("/content/Employee.zip")
a

dept_avg_income = a.groupby('experience')['income'].mean()
print(dept_avg_income)

highest_income_employee = a.loc[a['income'].idxmax()]
print(highest_income_employee)

lowest_income_employee = a.loc[a['income'].idxmin()]
print(lowest_income_employee)

a.describe()